version: '3.4'

services:
  node:
      image: sdc-node
      container_name: sdc-node
      depends_on:
        - mongo
      ports:
        - 3001:3001
      build:
        context: .
        dockerfile: node.Dockerfile
  mongo:
    image: sdc-mongo
    container_name: sdc-mongo
    ports:
      - 1234:27017
    environment:
      MONGO_INITDB_DATABASE: sdcrandr
    build:
      context: ../server/db/data/
      dockerfile: mongo.Dockerfile
    volumes: 
      - sdcrandr:/data/db
volumes:
  sdcrandr: